# Pys, Modules, and Data Science Intro

Welcome to this comprehensive guide! We will cover several essential Python topics with detailed explanations and examples:

1.  **Escape Sequences**: How to format strings with special characters.
2.  **File I/O**: Reading from and writing to files.
3.  **Modules and Packages**: Organizing code and using built-in/custom libraries.
4.  **NumPy**: A deep dive into Numerical Python, including Data Cleaning.
5.  **Pandas**: A deep dive into Data Analysis with Pandas, including Data Cleaning.

## 1. Escape Sequences

Escape sequences allow you to include special characters in strings that would otherwise be impossible or difficult to type. They always start with a backslash (`\`).

### Common Escape Sequences Table

| Escape Sequence | Description | Example |
| :--- | :--- | :--- |
| `\n` | Newline (Line Feed) | `print("Hello\nWorld")` |
| `\t` | Horizontal Tab | `print("Name:\tJohn")` |
| `\\` | Backslash | `print("C:\\Users")` |
| `\' `| Single Quote | `print('It\'s me')` |
| `\"` | Double Quote | `print("He said \"Hi\"")` |
| `\b` | Backspace | `print("Hello\bWorld")` (Removes 'o') |

In [1]:
print("Shopping_List:\t \n\t\"milk\"\n\t\"Egg\"\n\t\"Bread\"\nNote:Don't forget the \"receipt\"!")

Shopping_List:
	"milk"
	"Egg"
	"Bread"
Note:Don't forget the "receipt"!

In [2]:
print ("name:\t \njohn")

name:
john

In [4]:
print ("c:\\users")

c:\users

In [5]:
print ("hello\bworld")

hellworld

In [6]:
print('it\'s me')

it's me

In [7]:
print("he said \"hi\"")

he said "hi"

In [8]:
print("Hello World")

Hello World

In [9]:
print("Hello\nWorld")

Hello
World

In [10]:
print("Blessing\"s Bag")

Blessing"s Bag

In [11]:
print("C:\\Users\\Samson\\Documents\\NGiT\\trainings\\AIML\\other-files\\conditionals.py")

C:\Users\Samson\Documents\NGiT\trainings\AIML\other-files\conditionals.py

In [12]:
print("Hello\tWorld")

Hello	World

In [13]:
print("milk\nEgg\nBread")

milk
Egg
Bread

In [14]:
print("\"milk\"\n\"Egg\"\n\"Bread\"")

"milk"
"Egg"
"Bread"

In [15]:
print("line 1\nline 2\nline 3")

line 1
line 2
line 3

In [16]:
print("Hello\bWorld")

HellWorld

In [17]:
# --- Examples of Escape Sequences ---

# 1. Newline: Moves the cursor to the next line
print("Line 1\nLine 2\nLine 3")
print("-" * 20)

# 2. Tab: Adds a tab space (usually 4 spaces)
print("Column 1\tColumn 2\tColumn 3")
print("Data A\tData B\tData C")
print("-" * 20)

# 3. Quotes inside strings
# Using backslash to print double quotes inside a double-quoted string
print("The teacher said, \"Please submit your assignments by Friday.\"")
# Using backslash to print single quote inside a single-quoted string
print('It\'s a beautiful day to learn Python!')
print("-" * 20)

# 4. Backslash: Printing the backslash character itself
# This is very common in Windows file paths
print("C:\\Users\\Admin\\Documents\\Python_Projects")

Line 1
Line 2
Line 3
--------------------
Column 1	Column 2	Column 3
Data A	Data B	Data C
--------------------
The teacher said, "Please submit your assignments by Friday."
It's a beautiful day to learn Python!
--------------------
C:\Users\Admin\Documents\Python_Projects

In [18]:
print("-" * 2)

--

In [19]:
print("Note:\tDon't forget the \"receipt\"!")

Note:	Don't forget the "receipt"!

In [20]:
print("data A\tdata b")

data A	data b

In [21]:
print("n" * 20)

nnnnnnnnnnnnnnnnnnnn

### Task 1: Escape Sequences Practice
Write a single print statement that outputs the following text exactly as shown (pay attention to tabs and newlines):

```text
Shopping List:
	* "Milk"
	* "Eggs"
	* "Bread"
Note: Don't forget the \receipt\!
```

In [22]:
# Your code here
print("Shopping_List:\t \n\t\"milk\"\n\t\"Egg\"\n\t\"Bread\"\nNote:\tDon't forget the \"receipt\"!")

Shopping_List:
	"milk"
	"Egg"
	"Bread"
Note:	Don't forget the "receipt"!

## 2. Reading and Writing Files (File I/O)

File handling is a crucial part of any programming language. Python provides built-in functions to create, read, update, and delete files.

### The `open()` Function
The key function for working with files in Python is `open()`. It takes two main parameters: `filename` and `mode`.

### File Modes

| Mode | Description |
| :--- | :--- |
| `'r'` | **Read** - Default value. Opens a file for reading, error if the file does not exist. |
| `'a'` | **Append** - Opens a file for appending, creates the file if it does not exist. |
| `'w'` | **Write** - Opens a file for writing, creates the file if it does not exist. Overwrites existing content! |
| `'x'` | **Create** - Creates the specified file, returns an error if the file exists. |

### The `with` Statement
It is best practice to use the `with` statement when working with files. It automatically closes the file for you when you are done, even if an error occurs. This prevents memory leaks and file corruption.

In [23]:
filename = "logs.txt"
with open(filename,"r") as file:
    lines=file.readlines()
    for i, line in enumerate(lines,1):
        print(line.strip())

2026-01-10 08:15:23 INFO User login successful for user_id=1021
2026-01-10 08:16:01 INFO Data sync started
2026-01-10 08:16:05 ERROR Failed to connect to database
2026-01-10 08:16:07 INFO Retrying database connection
2026-01-10 08:16:12 ERROR Database connection timeout
2026-01-10 08:17:45 WARNING High memory usage detected
2026-01-10 08:18:02 INFO Scheduled job started
2026-01-10 08:18:09 ERROR File not found: config.yaml
2026-01-10 08:18:15 INFO Scheduled job completed
2026-01-10 08:19:30 INFO User logout successful for user_id=1021
2026-01-10 08:20:10 ERROR Permission denied while writing to disk
2026-01-10 08:21:00 INFO System health check passed

In [24]:
# --- Writing to a file ---
filename = "sample_data.py"

# 'w' mode overwrites any existing content
with open(filename, "w") as file:
    file.write("'My name is Python.\n'")
    file.write("'Python makes file handling very simple.\n'")
    file.write("'We are learning about the 'w' mode.\n'")

print(f"Successfully wrote to '{filename}'.")

Successfully wrote to 'sample_data.py'.

In [25]:
filename = "my_diary"
with open(filename,"w") as file:
    file.write("Learnt about escape sequence.\n")
    file.write("Read the material and practiced the examples.\n")
    file.write("Did the exercise on it without watching recap.\n")

print(f"successfully wrote to '{filename}'.")

with open(filename, "a") as file:
    file.write("My goal for tommorrow is to complete my outlined task.\n")

print(f"successfully appended to '{filename}'.")

with open(filename,"r") as file:
    lines = file.readlines()
    for i, line in enumerate(lines,1):
        print(f"Diary_entry: {line.strip()}")

successfully wrote to 'my_diary'.
successfully appended to 'my_diary'.

Diary_entry: Learnt about escape sequence.
Diary_entry: Read the material and practiced the examples.
Diary_entry: Did the exercise on it without watching recap.
Diary_entry: My goal for tommorrow is to complete my outlined task.

In [26]:
# --- Appending to a file ---
# 'a' mode adds content to the end of the file without deleting existing content
with open(filename, "a") as file:
    file.write("This line is appended using 'a' mode.\n")
    file.write("Notice how the previous content is still there!\n")

print(f"Successfully appended to '{filename}'.")

Successfully appended to 'my_diary'.

In [27]:
my_file = "wunmi.py"

with open(my_file, "a") as file:
    file.write("'My name is Wunmi and I am a python developer'\n")
    file.write("'I am currently learning file handling'\n")

In [ ]:
file_name = "wunmi.py"



with open(file-name, "r") as file:
    content = file.read()
    print(type(content))

In [ ]:
file_name = "wunmi.py"

with open(file_name, "r") as file:
    content = file.readlines()
    print(type(content))

<class 'list'>

In [ ]:
# --- Reading from a file ---

# Method 1: read() - Reads the entire file content as a single string
print("--- Method 1: read() ---")
with open(filename, "r") as file:
    content = file.read()
    print(content)

# Method 2: readlines() - Reads all lines into a list
print("\n--- Method 2: readlines() ---")
with open(filename, "r") as file:
    lines = file.readlines()
    print(f"Number of lines: {len(lines)}")
    for i, line in enumerate(lines, 1):
        print(f"Line {i}: {line.strip()}") # strip() removes the newline character at the end

In [ ]:
with open(filename,"r") as file:
    lines = file.readlines()
    for i, line in enumerate(lines,1):
        print(f"Diary_entry: {line.strip()}")

Diary_entry: Learnt about escape sequence.
Diary_entry: Read the material and practiced the examples.
Diary_entry: Did the exercise on it without watching recap.
Diary_entry: My goal for tommorrow is to complete my outlined task.

In [ ]:
with open(filename,"r") as file:
    content=file.read()
    print(content)

Learnt about escape sequence.
Read the material and practiced the examples.
Did the exercise on it without watching recap.
My goal for tommorrow is to complete my ouline to do task.

### Task 2: File I/O Practice
1. Create a file named `my_diary.txt`.
2. Write 3 lines about what you learned today.
3. Open the file again and append one more line about your goal for tomorrow.
4. Read the file and print each line with a prefix "Diary Entry: ".

In [ ]:
# Your code here
filename = "my_diary"
with open(filename,"w") as file:
    file.write("Learnt about escape sequence.\n")
    file.write("Read the material and practiced the examples.\n")
    file.write("Did the exercise on it without watching recap.\n")

print(f"successfully wrote to '{filename}'.")

with open(filename, "a") as file:
    file.write("My goal for tommorrow is to complete my outlined task.\n")

print(f"successfully appended to '{filename}'.")

with open(filename,"r") as file:
    lines = file.readlines()
    for i, line in enumerate(lines,1):
        print(f"Diary_entry: {line.strip()}")

successfully wrote to 'my_diary'.
successfully appended to 'my_diary'.
Diary_entry: Learnt about escape sequence.
Diary_entry: Read the material and practiced the examples.
Diary_entry: Did the exercise on it without watching recap.
Diary_entry: My goal for tommorrow is to complete my outlined task.

## 3. Modules and Packages

A **module** is simply a file containing Python code. A **package** is a directory of modules containing a special `__init__.py` file.

### Why use modules?
- **Reusability**: Write code once, use it everywhere.
- **Organization**: Keep your code clean and manageable.
- **Namespace**: Avoid variable name conflicts.

### Importing Modules
You can import modules in several ways:
1. `import module_name` (Access via `module_name.function()`)
2. `import module_name as alias` (Access via `alias.function()`)
3. `from module_name import function_name` (Access directly via `function_name()`)
4. `from module_name import *` (Imports everything - generally discouraged)

In [ ]:
import math
import random

my_list = [1,2,3,4,5,6,7,8]

random.choice(my_list)
math.sqrt(25)

5.0

In [ ]:
import math
print(math.sqrt (25))

5.0

In [ ]:
# --- Using Built-in Modules ---

import math
import random
import datetime as dt

# Math module
print(f"Square root of 25: {math.sqrt(25)}")
print(f"Factorial of 5: {math.factorial(5)}")

# Random module
print(f"Random number (1-100): {random.randint(1, 100)}")
choices = ['Apple', 'Banana', 'Cherry']
print(f"Random choice: {random.choice(choices)}")

# Datetime module
now = dt.datetime.now()
print(f"Current date and time: {now}")
print(f"Current year: {now.month}")

Square root of 25: 5.0
Factorial of 5: 120
Random number (1-100): 70
Random choice: Banana
Current date and time: 2026-03-02 00:36:32.815417
Current year: 3

In [ ]:
import math as mth
import datetime as dt

today_date = dt.datetime.now()
print(today_date)

mth.sqrt(25)

2026-02-28 18:33:23.003487

5.0

### Using a Custom Module
We have a file named `my_module.py` in the current directory. Let's use it.

In [ ]:
import my_module

# Accessing a variable
print(f"Greeting from module: {my_module.greeting}")

# Accessing a function
result = my_module.add_numbers(10, 20)
print(f"Result of addition: {result}")

need the my_module file

## 4. NumPy (Numerical Python)

NumPy is the fundamental package for scientific computing in Python. It provides support for arrays (matrices), which are much faster and more efficient than Python lists.

### Why NumPy?
- **Speed**: NumPy arrays are stored in contiguous memory locations.
- **Functionality**: Optimized built-in mathematical functions.
- **Convenience**: Easy to perform operations on entire arrays at once (broadcasting).

### Most Used NumPy Methods

| Method | Description | Example |
| :--- | :--- | :--- |
| `np.array(list)` | Creates a NumPy array from a python list | `arr = np.array([1, 2, 3])` |
| `np.zeros(shape)` | Creates an array filled with zeros | `np.zeros((2, 3))` |
| `np.ones(shape)` | Creates an array filled with ones | `np.ones((2, 3))` |
| `np.arange(start, stop, step)` | Creates an array with a range of values | `np.arange(0, 10, 2)` |
| `np.linspace(start, stop, num)` | Creates an array with `num` evenly spaced values | `np.linspace(0, 1, 5)` |
| `arr.reshape(new_shape)` | Changes the shape of an array | `arr.reshape(2, 3)` |
| `arr.shape` | Attribute returning the dimensions of the array | `(2, 3)` |
| `np.sum(arr)` | Calculates sum of all elements | `np.sum(arr)` |
| `np.mean(arr)` | Calculates average of all elements | `np.mean(arr)` |
| `np.max(arr)` / `np.min(arr)` | Finds maximum / minimum value | `np.max(arr)` |
| `np.random.rand(d0, d1)` | Generates random values between 0 and 1 | `np.random.rand(3, 2)` |

In [ ]:
rand=np.random.rand(1,10)
print(rand)

[[0.00866091 0.59462532 0.80783176 0.03821556 0.30969823 0.181656
  0.07978821 0.27194358 0.27644351 0.36384513]]

In [ ]:
arr=(5,6,3,4,6,7,9,8,10)
add=np.shape(arr)
print(add)

(9,)

In [ ]:
arr=np.array([5,6,3,4,6,7,9,8,10])

add=arr.reshape(3,3)
print(add)

[[ 5  6  3]
 [ 4  6  7]
 [ 9  8 10]]

In [ ]:
nip=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
dimen_2=nip.reshape(2,10)

print(dimen_2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

In [ ]:
arr=(5,6,3,4,6,7,8,10)
add=np.sum(arr)
print(add)

49

In [ ]:
arr=(5,6,3,4,6,7,8,10)
mean=np.mean(arr)
print(mean)

6.125

In [ ]:
d0=int(input("enter number"))
d1=int(input("enter number"))
ran=np.random.rand(d0,d1)
print(ran)

[[0.74161615 0.17252595]
 [0.34124813 0.39611797]
 [0.89765693 0.01280879]]

In [ ]:
arr=(5,6,3,4,6,7,8,10)
min=np.min(arr)
print(min)

3

In [ ]:
arr=(5,6,3,4,6,7,8,10)
max=np.max(arr)
print(max)

10

In [ ]:
zeros = np.zeros((3, 3))
print(f"\nZeros Array:\n{zeros}")

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
nor=np.zeros((2,2))
print(nor)

[[0. 0.]
 [0. 0.]]

In [ ]:
import numpy as np
pie=np.arange(1,20,1)
print(pie)

pp=np.linspace(0,1,5)
print(pp)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.   0.25 0.5  0.75 1.  ]

In [ ]:
import numpy as np
our_list =[1,2,3,4,5,6,7,8,9]
print(type(our_list))

new=np.array(our_list)
print(new)

<class 'list'>
[1 2 3 4 5 6 7 8 9]

In [ ]:
list1=[1,2,3]
list2=[4,5,6]

num=np.array([list1,list2] )
print(num)
print(num.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

In [ ]:
import my_module as np

arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr=np.shape(2,3)
print(arr)

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr_2d}")
print(f"Shape of 2D Array: {arr_2d.shape}")

2D Array:
[[1 2 3]
 [4 5 6]]
Shape of 2D Array: (2, 3)

In [ ]:
import numpy as np

# --- 1. Array Creation ---
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr_2d}")
print(f"Shape of 2D Array: {arr_2d.shape}")

# --- 2. Built-in Creation Functions ---
zeros = np.zeros((3, 3))
print(f"\nZeros Array:\n{zeros}")

range_arr = np.arange(0, 20, 2) # Start at 0, stop before 20, step 2
print(f"\nRange Array: {range_arr}")

# --- 3. Array Operations ---
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition (Broadcasting)
print(f"\na + b: {a + b}")
print(f"a * 2: {a * 2}")

# Statistics
print(f"\nSum: {np.sum(a)}")
print(f"Mean: {np.mean(a)}")
print(f"Max: {np.max(a)}")

1D Array: [1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]
Shape of 2D Array: (2, 3)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Range Array: [ 0  2  4  6  8 10 12 14 16 18]

a + b: [5 7 9]
a * 2: [2 4 6]

Sum: 6
Mean: 2.0
Max: 3

### NumPy Data Cleaning

Data cleaning is essential. In NumPy, we often deal with missing values represented as `NaN` (Not a Number).

Common tasks:
- Identifying `NaN` values: `np.isnan(arr)`
- Removing `NaN` values: Using boolean indexing
- Replacing `NaN` values: `np.nan_to_num(arr)` or custom logic

In [ ]:
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
has_nans = np.isnan(data_arr)
print(f"Is NaN mask: {has_nans}")

Is NaN mask: [False False  True False False  True]

In [ ]:
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
epp=data_arr[~has_nans]
print(epp)

[1. 2. 4. 5.]

In [ ]:
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
mean=np.nanmean(data_arr)
print(mean)

3.0

In [ ]:
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
mean=np.nanmean(data_arr)
new=np.nan_to_num(data_arr, nan=mean)
print(new)

[1. 2. 3. 4. 5. 3.]

In [ ]:
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
mean=np.nanmean(data_arr)
data_arr[np.isnan(data_arr)]=mean
print(data_arr)

[1. 2. 3. 4. 5. 3.]

In [ ]:
# --- Handling Missing Values in NumPy ---

# Create an array with NaN (Not a Number)
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
print(f"Original Array with NaNs: {data_arr}")

# Check for NaNs
has_nans = np.isnan(data_arr)
print(f"Is NaN mask: {has_nans}")

# Remove NaNs
clean_arr = data_arr[~has_nans] # ~ means 'not'
print(f"Array without NaNs: {clean_arr}")

# Replace NaNs with a value (e.g., 0)
replaced_arr = np.nan_to_num(data_arr, nan=0.0)
print(f"Array with NaNs replaced by 0: {replaced_arr}")

# Replace NaNs with the mean of valid elements
mean_val = np.nanmean(data_arr) # nanmean calculates mean ignoring NaNs
data_arr[np.isnan(data_arr)] = mean_val
print(f"Array with NaNs replaced by Mean ({mean_val}): {data_arr}")

Original Array with NaNs: [ 1.  2. nan  4.  5. nan]
Is NaN mask: [False False  True False False  True]
Array without NaNs: [1. 2. 4. 5.]
Array with NaNs replaced by 0: [1. 2. 0. 4. 5. 0.]
Array with NaNs replaced by Mean (3.0): [1. 2. 3. 4. 5. 3.]

### NumPy Practice Tasks (Data Cleaning Included)

**Task 1:** Create a NumPy array of numbers from 1 to 20. Reshape it into a 4x5 matrix (2D array) and print it.

**Task 2:** Create an array: `[10, 20, np.nan, 40, np.nan, 60]`. Find the sum of this array ignoring the NaNs (Hint: look for a specific function).

**Task 3:** Create a 1D array of 10 random numbers. Replace all values greater than 0.5 with 1.0 and all others with 0.0 (Binarization).

**Task 4:** Create a 3x3 array with `NaN` on the main diagonal. Replace these `NaN`s with the number -1.

In [ ]:
import numpy as np
list=[1,20]
print(type(list))

num_arr=np.array(list)
print(num_arr)

<class 'list'>
[ 1 20]

In [ ]:


# Task 1: Reshaping
# Your code here

num_arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
num_arr2=num_arr.reshape(4,5)
print(num_arr2)



# Task 2: Sum ignoring NaNs
# Your code here
hot=np.array([10,20,np.nan,40,np.nan,60])
replaced=np.nan_to_num(hot,nan=0.0)
print(replaced)

add=np.sum(replaced)
print(add)


# Task 3: Binarization
# Your code here
rand=np.random.rand(10)
print(rand)

for i in rand:
    if i > 0.5 :
        print(1.0)
    else:
        print(0.0)







# Task 4: Diagonal Replacement
# Your code here

task=np.array([np.nan,5,10,56,np.nan,2,12,22,np.nan,])
task2=task.reshape(3,3)
print(task2)

replace=np.nan_to_num(task2, nan=-1)
print(replace)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[10. 20.  0. 40.  0. 60.]
130.0
[0.50185483 0.93078484 0.258971   0.92766756 0.06761452 0.28980279
 0.96080861 0.7435849  0.71982282 0.4258171 ]
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
0.0
[[nan  5. 10.]
 [56. nan  2.]
 [12. 22. nan]]
[[-1.  5. 10.]
 [56. -1.  2.]
 [12. 22. -1.]]

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr_2d}")
print(f"Shape of 2D Array: {arr_2d.shape}")

arr_3d = np.array([['cup',2][3,'bag'][5,6]])
print(f'\n3D Array:\n{arr_3d}')
print(f"Shape of 3D Array: {arr_3d.shape}")

replaced_arr = np.nan_to_num(arr_3d, nan=-1)
print(f"Array with NaNs replaced by 0: {arr_3d}")

## 5. Pandas (Python Data Analysis Library)

Pandas is built on top of NumPy and provides high-performance, easy-to-use data structures and data analysis tools. The two primary data structures are **Series** (1D) and **DataFrame** (2D).

### Most Used Pandas Methods

| Method | Description | Example |
| :--- | :--- | :--- |
| `pd.DataFrame(data)` | Creates a DataFrame from a dictionary or list | `df = pd.DataFrame(data)` |
| `pd.read_csv(filename)` | Reads data from a CSV file | `df = pd.read_csv('data.csv')` |
| `df.head(n)` | Returns the first n rows | `df.head(5)` |
| `df.tail(n)` | Returns the last n rows | `df.tail(3)` |
| `df.info()` | Prints summary of the DataFrame (types, non-nulls) | `df.info()` |
| `df.describe()` | Generates descriptive statistics (mean, std, min, max) | `df.describe()` |
| `df.shape` | Returns dimensions (rows, columns) | `df.shape` |
| `df.columns` | Returns list of column names | `df.columns` |
| `df['col']` | Selects a single column | `df['Age']` |
| `df.loc[row, col]` | Access group of rows/cols by label | `df.loc[0, 'Name']` |
| `df.iloc[row, col]` | Access group of rows/cols by integer position | `df.iloc[0, 0]` |
| `df.drop(columns)` | Removes specified columns | `df.drop(columns=['Age'])` |
| `df.isnull().sum()` | Checks for missing values | `df.isnull().sum()` |
| `df.dropna()` | Drops rows with missing values | `df.dropna()` |
| `df.fillna(value)` | Fills missing values | `df.fillna(0)` |
| `df.duplicated()` | Checks for duplicates | `df.duplicated()` |
| `df.drop_duplicates()` | Removes duplicates | `df.drop_duplicates()` |

In [ ]:
import pandas as pd

# --- 1. Creating a DataFrame ---
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [50000, 60000, 55000, 70000, 65000]
}
jj=pd.DataFrame(data)
print(jj)

      Name  Age         City  Salary
0    Alice   24     New York   50000
1      Bob   27  Los Angeles   60000
2  Charlie   22      Chicago   55000
3    David   32      Houston   70000
4      Eve   29      Phoenix   65000

In [ ]:
jj.head()

      Name  Age         City  Salary
0    Alice   24     New York   50000
1      Bob   27  Los Angeles   60000
2  Charlie   22      Chicago   55000
3    David   32      Houston   70000
4      Eve   29      Phoenix   65000

In [ ]:
jj.tail(2)

    Name  Age     City  Salary
3  David   32  Houston   70000
4    Eve   29  Phoenix   65000

In [ ]:
jj.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Salary  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [ ]:
import pandas as pd

# --- 1. Creating a DataFrame ---
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [50000, 60000, 55000, 70000, 65000]
}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

# --- 2. Inspecting Data ---
print("\n--- First 2 rows (head) ---")
print(df.head(2))

print("\n--- DataFrame Info ---")
df.info()

print("\n--- Descriptive Statistics ---")
print(df.describe())

# --- 3. Selecting Data ---
print("\n--- Selecting 'Name' and 'Salary' ---")
print(df[['Name', 'Salary']])

# --- 4. Filtering Data ---
print("\n--- Employees older than 25 ---")
filtered_df = df[df['Age'] > 25]
print(filtered_df)

--- Original DataFrame ---
      Name  Age         City  Salary
0    Alice   24     New York   50000
1      Bob   27  Los Angeles   60000
2  Charlie   22      Chicago   55000
3    David   32      Houston   70000
4      Eve   29      Phoenix   65000

--- First 2 rows (head) ---
    Name  Age         City  Salary
0  Alice   24     New York   50000
1    Bob   27  Los Angeles   60000

--- DataFrame Info ---
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Salary  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

--- Descriptive Statistics ---
             Age       Salary
count   5.000000      5.00000
mean   26.800000  60000.00000
std     3.962323   7905.69415
min    22.000000  50000.00000
25%    24.000000  55000.00000
50%    27.000000  60000.00000
75%    29.000000  65000.00000
max    32.000000  70000.00000

--- Selecting 'Name' and 'Salary' ---
      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   55000
3    David   70000
4      Eve   65000

--- Employees older than 25 ---
    Name  Age         City  Salary
1    Bob   27  Los Angeles   60000
3  David   32      Houston   70000
4    Eve   29      Phoenix   65000

### Pandas Data Cleaning

Data cleaning is a critical step in data analysis. Real-world data is often messy, containing missing values, duplicates, or incorrect data types.

Common tasks:
- **Handling Missing Data**: `dropna()`, `fillna()`
- **Removing Duplicates**: `drop_duplicates()`
- **Data Type Conversion**: `astype()`
- **Renaming Columns**: `rename()`

In [ ]:
# --- Pandas Data Cleaning Examples ---

# Create a messy DataFrame
messy_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', None],
    'Age': [25, np.nan, 30, 25, 22],
    'Score': ['85', '90', 'NaN', '85', '70'] # Score is string type!
}
df_messy = pd.DataFrame(messy_data)

print("--- Messy DataFrame ---")
print(df_messy)

# 1. Check for missing values
print("\n--- Missing Values Count ---")
print(df_messy.isnull().sum())

# 2. Remove duplicates
df_clean = df_messy.drop_duplicates()
print("\n--- After Removing Duplicates ---")
print(df_clean)

# 3. Handling Missing Values
# Fill Name with 'Unknown'
df_clean['Name'] = df_clean['Name'].fillna('Unknown')
# Fill Age with mean age
mean_age = df_clean['Age'].mean()
df_clean['Age'] = df_clean['Age'].fillna(mean_age)

print("\n--- After Filling Missing Values ---")
print(df_clean)

# 4. Data Type Conversion
# 'Score' is object (string) because of 'NaN' string. Let's fix it.
# First, coerce errors to NaN (turn string 'NaN' to actual NaN)
df_clean['Score'] = pd.to_numeric(df_clean['Score'], errors='coerce')

# Now fill the new NaN in score with 0 or mean
df_clean['Score'] = df_clean['Score'].fillna(0)

print("\n--- Final Cleaned DataFrame ---")
print(df_clean)
print(df_clean.info())

--- Messy DataFrame ---
      Name   Age Score
0    Alice  25.0    85
1      Bob   NaN    90
2  Charlie  30.0   NaN
3    Alice  25.0    85
4      NaN  22.0    70

--- Missing Values Count ---
Name     1
Age      1
Score    0
dtype: int64

--- After Removing Duplicates ---
      Name   Age Score
0    Alice  25.0    85
1      Bob   NaN    90
2  Charlie  30.0   NaN
4      NaN  22.0    70

--- After Filling Missing Values ---
      Name        Age Score
0    Alice  25.000000    85
1      Bob  25.666667    90
2  Charlie  30.000000   NaN
4  Unknown  22.000000    70

--- Final Cleaned DataFrame ---
      Name        Age  Score
0    Alice  25.000000   85.0
1      Bob  25.666667   90.0
2  Charlie  30.000000    0.0
4  Unknown  22.000000   70.0
<class 'pandas.DataFrame'>
Index: 4 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      float64
 2   Score   4 non-null      float64
dtypes: float64(2), str(1)
memory usage: 128.0 bytes
None

### Pandas Practice Tasks (Data Cleaning Included)

**Task 1:** Create a DataFrame with columns `Product`, `Price`, and `Stock`. Include some `None` values and duplicate rows.

**Task 2:** Clean the DataFrame from Task 1: Remove duplicates and fill missing `Stock` values with 0.

**Task 3:** Add a new column called `Total_Value` (Price * Stock).

**Task 4:** Calculate the average price of the products. If there are any missing `Price` values, fill them with the median price before calculating.

In [ ]:

replace=np.nan_to_num(cleanRegister, nan=0)

df_clean['Name'] = df_clean['Name'].fillna('Unknown')

In [32]:
import numpy as np
import pandas as pd

In [38]:
# Task 1: Create Messy DataFrame
# Your code here
register_data={
    'Product':['soap','soap','none','cap','gel'],
    'price':[20,20,np.nan,1000,150],
    'stock':[5,5,2,35,np.nan]
    
}
my_register=pd.DataFrame(register_data)
print('----my_register------')
print(my_register)

# Task 2: Clean Data
# Your code here
cleanRegister=my_register.drop_duplicates()
print(cleanRegister)

cleanRegister['stock']=cleanRegister["stock"].fillna(0)
print('------cleanRegister-----')
print(cleanRegister)

# Task 3: Calculate Total Value
# Your code here
cleanRegister['total_value']=cleanRegister["price"]*cleanRegister['stock']
print('---------total value--------')
print(cleanRegister)

# Task 4: Average Price with Fill
# Your code here
median_price = cleanRegister['price'].median()
cleanRegister['price']= cleanRegister['price'].fillna(median_price)

average_price=cleanRegister['price'].mean()
print('-------average price------')
print(average_price)

----my_register------
  Product   price  stock
0    soap    20.0    5.0
1    soap    20.0    5.0
2    none     NaN    2.0
3     cap  1000.0   35.0
4     gel   150.0    NaN
  Product   price  stock
0    soap    20.0    5.0
2    none     NaN    2.0
3     cap  1000.0   35.0
4     gel   150.0    NaN
------cleanRegister-----
  Product   price  stock
0    soap    20.0    5.0
2    none     NaN    2.0
3     cap  1000.0   35.0
4     gel   150.0    0.0
---------total value--------
  Product   price  stock  total_value
0    soap    20.0    5.0        100.0
2    none     NaN    2.0          NaN
3     cap  1000.0   35.0      35000.0
4     gel   150.0    0.0          0.0
-------average price------
330.0